{
    "name": "DS Project Planning",
    "version": "15.0.1.0.0",
    "description": "",
    "summary": "Manage project plan",
    "author": "Dsoft",
    "website": "https://d-soft.com.vn",
    "category": "Project",
    "license": "AGPL-3",
    "depends": ['base', 'project', 'mail', 'web_domain_field'],
    "application": True,
    "auto_install": False,
    "data": [
        "security/planning_security.xml",
        "security/ir.model.access.csv",
        "views/planning_views.xml",
        "views/planning_menu.xml",
        "views/project_task_views.xml",
        "views/project_menu.xml",
    ],
}
