{
    "name": "DS Print Contract & Send Email",
    "version": "15.0.1.0.0",
    "category": "Human Resources",
    'author': 'nhannv',
    'website': 'https://d-soft.com.vn/',
    "license": "AGPL-3",
    "summary": """Print Contract Detail for the employee.
                Send Email with attach Contract file to Employee""",
    "depends": ["hr", "hr_contract", "hr_employee_updation", "hr_contract_types", "base"],
    "data": ["views/contract_report.xml",
             "views/probationary_contract_report.xml",
             "views/internship_contract_report.xml",
             "views/duration_contract_view.xml",
             "views/information_security_commit_report.xml",
             "views/send_email_contract.xml",
             "views/collaborators_contract_report.xml",
             "report/contract_qweb_report.xml",
             "report/information_security_commit_report.xml",
             "data/offical_labor_contract_mail_template.xml",
             "data/probationary_contract_mail_template.xml",
             "data/internship_contract_mail_template.xml",
             "data/collaborator_contract_mail_template.xml",
             "views/annex_contract_report.xml",
             "data/annex_contract_mail_template.xml",
             "views/res_company_views.xml",
             "views/annex_contract_gross_report.xml",
             "views/contract_gross_report.xml",
             "data/annex_contract_gross_mail_template.xml",
             "data/offical_labor_contract_gross_mail_template.xml",
             "views/probationary_contract_gross_report.xml",
             "data/probationary_contract_gross_mail_template.xml",
             "views/mirai_contract_gross_report.xml",
             ],
    'assets': {
        'web.report_assets_common': [
            'ds_print_contract/static/src/css/report.css',
        ],
    },
    "installable": True,
    'auto_install': False,
    'application': False,
}
